baseURL = 'https://dpadevteam.github.io/dpa/'
languageCode = 'en-us'
title = 'Digital Privacy Advocacy'
# theme = "ananke"
theme = "hugo-coder"

[params]
  author = "Digital Privacy Advocacy"
  info = "Welcome to the blog!"
  description = "An informational blog that advocates for the proper handling of one's digital privacy."
  keywords = "blog,privacy,informational, digital privacy, digital privacy advocacy"
  avatarurl = "images/globe.png"

#   faviconSVG = "/img/favicon.svg"
#   favicon_32 = "/img/favicon-32x32.png"
#   favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false
  customCSS = ["css/override.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[services]
  [services.googleAnalytics]
    ID = 'G-BEB5WTKZ2M'

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
# [[menu.main]]
#   name = "About"
#   weight = 2
#   url = "about/"

[markup.goldmark.renderer]
  unsafe = true

[[params.social]]
  name = "Facebook"
  icon = "fa-brands fa-x-facebook fa-2x"
  weight = 3
  url = "https://www.facebook.com/people/Digital-Privacy-Advocacy/61556919033899/"

[params.giscus] # https://giscus.app
  repo = "dpadevteam/dpa"
  repoID = "R_kgDOLbbfWQ"
  category = "Comments"
  categoryID = "DIC_kwDOLbbfWc4CePCK"
  mapping = "og:title"
  term = ""
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "1"
  inputPosition = "top"
  theme = "cobalt"
  lang = "en"
  loading = "lazy"

